language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:niko2040/e19'
          packages:
            - libefl-dev
            - python3-jinja2
      env:
        - MATRIX_EVAL=""

  exclude: # macOS builds fail randomly because of travis itself
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install efl"


before_install:
  - eval "${MATRIX_EVAL}"

script: ./scripts/ci-build.sh
