name: Eovim CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './src ./include'
        extensions: 'c,h'
        clangFormatVersion: 12

    - name: Lint Additional Neovim Runtime
      uses: reviewdog/action-vint@v1
      with:
        github_token: ${{ secrets.github_token }}
        level: error
        reporter: github-pr-review

    # Install compile-time dependencies
    - name: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install --yes libefl-all-dev
        sudo apt-get install --yes libmsgpack-dev
        sudo apt-get install --yes cmake
        sudo apt-get install --yes build-essential

    - name: compile
      run: |
        src_dir=$(pwd)
        mkdir -p build
        cd build
        cmake -G "Unix Makefiles" -DWITH_WERROR=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr "$src_dir"
        make -j$(nproc)
        make DESTDIR="$src_dir/AppDir" install

    - name: generate AppImage
      run: |
        env LIBDIR=/usr/lib/x86_64-linux-gnu sh -x scripts/make-appimage.sh AppDir Eovim.appimage nightly

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Eovim-Snapshot
        path: './Eovim.appimage.zsync'
